package com.kinotor.tiar.kinotor.items;

/**
 * Created by Tiar on 30.01.2018.
 */

public class ItemCatalogUrls {
    private final String[] cKoshara = {"CAMRIP / TS",
            "WEBRIP / WEB-DL",
            "HDRIP / BDRIP",
            "ОТЕЧЕСТВЕННЫЕ ФИЛЬМЫ",
            "ЗАРУБЕЖНЫЕ ФИЛЬМЫ",
            "СЕРИАЛЫ"};
    private final String[] cAmcet = {"Биография",
            "Боевик",
            "Вестерн",
            "Военный",
            "Детектив",
            "Детский",
            "Для взрослых",
            "Документальный",
            "Драма",
            "Игра",
            "История",
            "Комедия",
            "Концерт",
            "Короткометражка",
            "Криминал",
            "Мелодрама",
            "Музыка",
            "Мюзикл",
            "Новости",
            "Приключения",
            "Реальное ТВ",
            "Семейный",
            "Спорт",
            "Ток-шоу",
            "Триллер",
            "Ужасы",
            "Фантастика",
            "Фильм-нуар",
            "Фэнтези"};
    private final String[] cKosharaUrl = {Statics.KOSHARA_URL + "/nerufilm/camrip/",
            Statics.KOSHARA_URL + "/nerufilm/webrips/",
            Statics.KOSHARA_URL + "/nerufilm/hd/",
            Statics.KOSHARA_URL + "/rufilm/",
            Statics.KOSHARA_URL + "/nerufilm/",
            Statics.KOSHARA_URL + "/serial/"};
    private final String[] cAmcetUrl = {Statics.AMCET_URL + "/biography/",
            Statics.AMCET_URL + "/smash-hit/",
            Statics.AMCET_URL + "/western/",
            Statics.AMCET_URL + "/military/",
            Statics.AMCET_URL + "/detective/",
            Statics.AMCET_URL + "/childs/",
            Statics.AMCET_URL + "/adults/",
            Statics.AMCET_URL + "/documentary/",
            Statics.AMCET_URL + "/drama/",
            Statics.AMCET_URL + "/game/",
            Statics.AMCET_URL + "/story/",
            Statics.AMCET_URL + "/comedy/",
            Statics.AMCET_URL + "/concert/",
            Statics.AMCET_URL + "/short/",
            Statics.AMCET_URL + "/crime/",
            Statics.AMCET_URL + "/melodrama/",
            Statics.AMCET_URL + "/music/",
            Statics.AMCET_URL + "/musical/",
            Statics.AMCET_URL + "/news/",
            Statics.AMCET_URL + "/adventure/",
            Statics.AMCET_URL + "/real-tv/",
            Statics.AMCET_URL + "/family/",
            Statics.AMCET_URL + "/sport/",
            Statics.AMCET_URL + "/show/",
            Statics.AMCET_URL + "/thriller/",
            Statics.AMCET_URL + "/horror/",
            Statics.AMCET_URL + "/fantastic/",
            Statics.AMCET_URL + "/film-noir/",
            Statics.AMCET_URL + "/fantasy/"};
    private final String[] cAmcetID = {"5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33"};
    private final String[] sortAmcet = {"по умолчанию",
            "по дате",
            "по алфавиту",
            "по рейтингу",
            "по просмотрам",
            "по комментариям",
            "по году",
            "по длительности",
            "по Кинопоиск`у",
            "по IMDb"};
    private final String[] sortAmcetID = {"defaultsort",
            "date",
            "title",
            "rating",
            "views",
            "comm",
            "year",
            "time",
            "kp",
            "imdb"};
    private final String[] sortAmcetYear = {"2018",
            "2017",
            "2016",
            "2015",
            "2014",
            "2013",
            "2012",
            "2011",
            "2010",
            "2009",
            "2008",
            "2007",
            "2006",
            "2005",
            "2004",
            "2003",
            "2002",
            "2001",
            "2000",
            "1999",
            "1998",
            "1997",
            "1996",
            "1995",
            "1994",
            "1993",
            "1992",
            "1991",
            "1990",
            "1989",
            "1988",
            "1987",
            "1986",
            "1985",
            "1984",
            "1983",
            "1982",
            "1981",
            "1980",
            "1979",
            "1978",
            "1977",
            "1976",
            "1975",
            "1974",
            "1973",
            "1972",
            "1971",
            "1970",
            "1969",
            "1968",
            "1967",
            "1966",
            "1965",
            "1964",
            "1963",
            "1962",
            "1961",
            "1960",
            "1959",
            "1958",
            "1957",
            "1956",
            "1955",
            "1954",
            "1953",
            "1952",
            "1951",
            "1950",
            "1949",
            "1948",
            "1947",
            "1946",
            "1945",
            "1944",
            "1943",
            "1942",
            "1941",
            "1940",
            "1939",
            "1938",
            "1937",
            "1936",
            "1935",
            "1934",
            "1933",
            "1932",
            "1931",
            "1930",
            "1929",
            "1928",
            "1927",
            "1926",
            "1925",
            "1922",
            "1921",
            "1916",
            "1915"};
    private final String[] sortAmcetCountry = {"Австралия",
            "Австрия",
            "Азербайджан",
            "Албания",
            "Алжир",
            "Ангола",
            "Аргентина",
            "Армения",
            "Аруба",
            "Афганистан",
            "Багамы",
            "Бангладеш",
            "Бахрейн",
            "Беларусь",
            "Бельгия",
            "Болгария",
            "Боливия",
            "Босния-Герцеговина",
            "Ботсвана",
            "Бразилия",
            "Бутан",
            "Великобритания",
            "Венгрия",
            "Венесуэла",
            "Вьетнам",
            "Гаити",
            "Гана",
            "Германия",
            "Германия(ГДР)",
            "Германия(ФРГ)",
            "Гонконг",
            "Греция",
            "Грузия",
            "Дания",
            "Доминикана",
            "Египет",
            "Замбия",
            "Израиль",
            "Индия",
            "Индонезия",
            "Иордания",
            "Ирак",
            "Иран",
            "Ирландия",
            "Исландия",
            "Испания",
            "Италия",
            "Казахстан",
            "Камбоджа",
            "Камерун",
            "Канада",
            "Катар",
            "Кения",
            "Кипр",
            "Китай",
            "Колумбия",
            "Конго",
            "КореяСеверная",
            "КореяЮжная",
            "Куба",
            "Кыргызстан",
            "Лаос",
            "Латвия",
            "Либерия",
            "Ливан",
            "Ливия",
            "Литва",
            "Лихтенштейн",
            "Люксембург",
            "Мавритания",
            "Мадагаскар",
            "Макао",
            "Македония",
            "Малайзия",
            "Мальта",
            "Марокко",
            "Мексика",
            "Монако",
            "Монголия",
            "Намибия",
            "Непал",
            "Нидерланды",
            "НоваяЗеландия",
            "Норвегия",
            "ОАЭ",
            "ОстровМэн",
            "Палестина",
            "Панама",
            "Папуа-НоваяГвинеявинея",
            "Парагвай",
            "Перу",
            "Польша",
            "Португалия",
            "ПуэртоРико",
            "Реюньон",
            "Россия",
            "Руанда",
            "Румыния",
            "СССР",
            "США",
            "СаудовскаяАравия",
            "Сербия",
            "Сингапур",
            "Словакия",
            "Словения",
            "Таджикистан",
            "Таиланд",
            "Тайвань",
            "Танзания",
            "Тунис",
            "Турция",
            "Уганда",
            "Узбекистан",
            "Украина",
            "Уругвай",
            "Фиджи",
            "Филиппины",
            "Финляндия",
            "Франция",
            "Хорватия",
            "Черногория",
            "Чехия",
            "Чехословакия",
            "Чили",
            "Швейцария",
            "Швеция",
            "Шри-Ланка",
            "Эквадор",
            "Эстония",
            "ЮАР",
            "Югославия",
            "Югославия",
            "Ямайка",
            "Япония"};
    private final String[] sortAnivost = {"ТВ",
            "ТВ-спэшл",
            "OVA",
            "ONA",
            "Полнометражный фильм",
            "Короткометражный фильм"};
    private final String[] sortAnivostUrl = {Statics.ANIMEVOST_URL + "/tip/tv/",
            Statics.ANIMEVOST_URL + "/tip/tv-speshl/",
            Statics.ANIMEVOST_URL + "/tip/ova/",
            Statics.ANIMEVOST_URL + "/tip/ona/",
            Statics.ANIMEVOST_URL + "/tip/polnometrazhnyy-film/",
            Statics.ANIMEVOST_URL + "/tip/korotkometrazhnyy-film/"};
    private final String[] cAnimevost = {"Боевые искусства",
            "Война",
            "Драма",
            "Детектив",
            "История",
            "Комедия",
            "Меха",
            "Мистика",
            "Махо-сёдзё",
            "Музыкальный",
            "Повседневность",
            "Приключения",
            "Пародия",
            "Романтика",
            "Сёнэн",
            "Сёдзё",
            "Спорт",
            "Сказка",
            "Сёдзё-ай",
            "Сёнэн-ай",
            "Самураи",
            "Триллер",
            "Ужасы",
            "Фантастика",
            "Фэнтези",
            "Школа",
            "Этти"};
    private final String[] cAnimevostUrl = {Statics.ANIMEVOST_URL + "/zhanr/boyevyye-iskusstva/",
            Statics.ANIMEVOST_URL + "/zhanr/voyna/",
            Statics.ANIMEVOST_URL + "/zhanr/drama/",
            Statics.ANIMEVOST_URL + "/zhanr/detektiv/",
            Statics.ANIMEVOST_URL + "/zhanr/istoriya/",
            Statics.ANIMEVOST_URL + "/zhanr/komediya/",
            Statics.ANIMEVOST_URL + "/zhanr/mekha/",
            Statics.ANIMEVOST_URL + "/zhanr/mistika/",
            Statics.ANIMEVOST_URL + "/zhanr/makho-sedze/",
            Statics.ANIMEVOST_URL + "/zhanr/muzykalnyy/",
            Statics.ANIMEVOST_URL + "/zhanr/povsednevnost/",
            Statics.ANIMEVOST_URL + "/zhanr/priklyucheniya/",
            Statics.ANIMEVOST_URL + "/zhanr/parodiya/",
            Statics.ANIMEVOST_URL + "/zhanr/romantika/",
            Statics.ANIMEVOST_URL + "/zhanr/senen/",
            Statics.ANIMEVOST_URL + "/zhanr/sedze/",
            Statics.ANIMEVOST_URL + "/zhanr/sport/",
            Statics.ANIMEVOST_URL + "/zhanr/skazka/",
            Statics.ANIMEVOST_URL + "/zhanr/sedze-ay/",
            Statics.ANIMEVOST_URL + "/zhanr/senen-ay/",
            Statics.ANIMEVOST_URL + "/zhanr/samurai/",
            Statics.ANIMEVOST_URL + "/zhanr/triller/",
            Statics.ANIMEVOST_URL + "/zhanr/uzhasy/",
            Statics.ANIMEVOST_URL + "/zhanr/fantastika/",
            Statics.ANIMEVOST_URL + "/zhanr/fentezi/",
            Statics.ANIMEVOST_URL + "/zhanr/shkola/",
            Statics.ANIMEVOST_URL + "/zhanr/etti/"};
    private final String[] sortAnimevostYear = {"1971",
            "1977",
            "1980",
            "1984",
            "1991",
            "1992",
            "1993",
            "1994",
            "1995",
            "1996",
            "1997",
            "1998",
            "1999",
            "2000",
            "2001",
            "2002",
            "2003",
            "2004",
            "2005",
            "2006",
            "2007",
            "2008",
            "2009",
            "2010",
            "2011",
            "2012",
            "2013",
            "2014",
            "2015",
            "2016",
            "2017",
            "2018"};

    public String mult(String catalog) {
        if (catalog.equals("koshara"))
            return Statics.KOSHARA_URL + "/index.php?do=search&subaction=search&story=%EC%F3%EB%FC%F2%F4%E8%EB%FC%EC";
        if (catalog.equals("amcet"))
            return Statics.AMCET_URL + "/cartoon/";

        else return null;
    }

    public String film(String catalog) {
        if (catalog.equals("koshara"))
            return Statics.KOSHARA_URL + "/nerufilm/";
        if (catalog.equals("amcet"))
            return Statics.AMCET_URL + "/films/";

        else return null;
    }

    public String serial(String catalog) {
        if (catalog.equals("koshara"))
            return Statics.KOSHARA_URL + "/serial/";
        if (catalog.equals("amcet"))
            return Statics.AMCET_URL + "/series/";
        else return null;
    }

    public String anime(String catalog) {
        if (catalog.equals("koshara"))
            return Statics.KOSHARA_URL + "/index.php?do=search&subaction=search&story=%EC%F3%EB%FC%F2%F4%E8%EB%FC%EC";
        if (catalog.equals("amcet"))
            return Statics.AMCET_URL + "/anime/";
        else return null;
    }

    public String[] getGenre(String catalog) {
        if (catalog.equals("koshara"))
            return cKoshara;
        if (catalog.equals("amcet"))
            return cAmcet;
        if (catalog.equals("animevost"))
            return cAnimevost;
        else return null;
    }

    public String[] getGenreUrl(String catalog) {
        if (catalog.equals("koshara"))
            return cKosharaUrl;
        if (catalog.equals("amcet"))
            return cAmcetUrl;
        if (catalog.equals("amcetID"))
            return cAmcetID;
        if (catalog.equals("animevost"))
            return cAnimevostUrl;
        else return null;
    }

    public String[] getSortName(String catalog) {
        if (catalog.equals("amcet"))
            return sortAmcet;
        if (catalog.equals("animevost"))
            return sortAnivost;
        else return null;
    }

    public String[] getSortUrl(String catalog) {
        if (catalog.equals("amcet"))
            return sortAmcetID;
        if (catalog.equals("animevost"))
            return sortAnivostUrl;
        else return null;
    }

    public String[] getYear(String catalog) {
        if (catalog.equals("amcet"))
            return sortAmcetYear;
        if (catalog.equals("animevost"))
            return sortAnimevostYear;
        else return null;
    }

    public String[] getSortAmcetCountry() {
        return sortAmcetCountry;
    }
}
